<?php
  /*
  * implimentation of hook_hook_info_alter()
  */
  function nycc_terms_conditions_form_alter(&$form, &$form_state, $form_id)
  {
    if($form_id == 'marketplace_for_sale_node_form'){
      // Add a checkbox to registration form about agreeing to terms of use.
      $form['terms_of_use'] = array(
        '#type' => 'checkbox',
        '#title' => "I agree with the website's <a href='/termsandconditions' target='_blank'>terms and conditions.</a>",
        '#required' => TRUE,
      );  	
    }
  }
  
  function nycc_terms_conditions_help($path, $args)
  {
  	if($path == 'admin/help#termsandconditions'){
  		return t('Terms and conditions allows an admin to set terms and conditions that a user must agree to on the marketplace.
  		  It also adds a required check box before the user is able to post an item.');
  	}
  }
  
  function get_termsandconditions_page_contents() {
	$termsandconditions_message = variable_get('termsandconditions_text', array('value' => '', 'format' => NULL));
    
    return $termsandconditions_message['value'];
  }
    
  function nycc_terms_conditions_menu(){
  	$items = array();
	
	$items['admin/config/nycc/terms-and-conditions'] = array(
	  'title' => 'Terms and conditions',
	  'description' => 'Configuration for the terms and conditions module',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('termsandconditions_form'),
	  'access arguments' => array('access administration pages'),
      'type' => MENU_NORMAL_ITEM,
	);
	$items['termsandconditions'] = array(
      'title' => variable_get('termsandconditions_pageTitle', 'Marketplace terms and conditions'),
      'page callback' => 'get_termsandconditions_page_contents',
      'access callback' => 'user_is_logged_in',
      'type' => MENU_NORMAL_ITEM,
    );
	 
	return $items;
  }
  
  function termsandconditions_form($form, &$form_state){
  	$form['termsandconditions_title'] = array(
	  '#type' => 'textfield',
      '#title' => t('Page Title'),
      '#default_value' => variable_get('termsandconditions_pageTitle', 'Marketplace terms and conditions'),
      '#size' => 60,
      '#maxlength' => 256,
      '#required' => TRUE,
      '#description' => t('The title for the marketplace terms and condition page'),
	);
	
	$termsandconditions_message = variable_get('termsandconditions_text', array('value' => '', 'format' => NULL));
	
  	$form['termsandconditions_text'] = array(
  	  '#type'=>'text_format',
  	  '#title' => t('Terms and condition text'),
  	  '#required' => TRUE,
  	  '#default_value' => $termsandconditions_message['value'],
  	  '#description' => t('The terms and conditions text for the marketplace.'),
  	  '#format' => isset($site_map_message['format']) ? $site_map_message['format'] : NULL,
	);
	
	return system_settings_form($form);
  }