name = Standard 3 col
description = A 3 column interior page
template = standard3col-layout

; Regions
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

regions[topsearch]		= Top Search
regions[topmenu]		= Top Menu
regions[topbar]			= Top Bar

regions[3_col_left]		= 3 Col Left Column
regions[3_col_right]	= 3 Col Right Column

; Styles
stylesheets[all][] = css/layouts/standard3col/standard3col.layout.css
stylesheets[all][] = css/layouts/standard3col/standard3col.layout.no-query.css

