<?php
/*
 * DD 
 * Just add the nycc 'configuration' heading so that it's available to our other modules
*/
function nycc_menu(){
	// Add the base 'NYCC' configuration
	$items = array();
	$items['admin/config/nycc'] = array(
		'title' => 'NYCC',
		'description' => 'NYCC Module Configuration',
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer site configuration'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);
	return $items;
}