name = Home 3 Col
description = A 3 column page, with a full width content area
template = home3col-layout

; Regions
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

regions[topsearch]		= Top Search
regions[topmenu]		= Top Menu
regions[topbar]			= Top Bar

regions[3_col_left]		= Left Hand Column
regions[3_col_right]	= Right Hand Column
regions[3_col_center]	= Center Column

; Styles
stylesheets[all][] = css/layouts/home3col/home3col.layout.css
stylesheets[all][] = css/layouts/home3col/home3col.layout.no-query.css