name = service-home
description = Similar to homepage layout, but includes page titles and other includes
template = service-home-layout

; Regions
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

regions[topsearch]		= Top Search
regions[topmenu]		= Top Menu
regions[topbar]			= Top Bar

regions[home_news]		= Home News Summary
regions[home_right]		= Home Column Right
regions[home_main]		= Home Main Column
regions[home_full] 		= Full Width Column

; Styles
stylesheets[all][] = css/layouts/service-home/service-home.layout.css
stylesheets[all][] = css/layouts/service-home/service-home.layout.no-query.css

; Scripts
scripts[] = js/home-news-respond.js