name = Full width
description = A full width interior page
template = fullwidth-layout

; Regions
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

regions[topsearch]		= Top Search
regions[topmenu]		= Top Menu
regions[topbar]			= Top Bar


; Styles
stylesheets[all][] = css/layouts/fullwidth/fullwidth.layout.css
stylesheets[all][] = css/layouts/fullwidth/fullwidth.layout.no-query.css

