<?php
  /*
  * implimentation of hook_hook_info_alter()
  */
  function nycc_mailurlrewrite_mail_alter(&$message) {

    $currentmail  = $message['body'];
    $currenturl = array(variable_get('nycc_urlfrom'));
    $newurl   = array(variable_get('nycc_urlto'));

    $newmail = str_replace($currenturl, $newurl, $currentmail);

    $message['body'] = $newmail;

  }
  
  
  function nycc_mailurlrewrite_help($path, $args)
  {
  	if($path == 'admin/help#mailurlrewrite'){
  		return t('This allows you to replace the internal URL with an external one.');
  	}
  }
    
  function nycc_mailurlrewrite_menu(){
  	$items = array();
	
	$items['admin/config/nycc/mailurlrewrite'] = array(
	  'title' => 'mail url rewrite',
	  'description' => 'Configuration for the mail url rewrite module',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('nycc_mailurlrewrite_form'),
	  'access arguments' => array('access administration pages'),
      'type' => MENU_NORMAL_ITEM,
	);
	 
	return $items;
  }
  
  function nycc_mailurlrewrite_form($form, &$form_state){
  	$form['mailurlrewrite_nycc_urlfrom'] = array(
	  '#type' => 'textfield',
      '#title' => t('Page Title'),
      '#default_value' => variable_get('nycc_urlfrom', 'nyccintranet'),
      '#size' => 60,
      '#maxlength' => 256,
      '#required' => TRUE,
      '#description' => t('The current internal url for the site'),
	);
	
  	$form['mailurlrewrite_nycc_urlto'] = array(
	  '#type' => 'textfield',
      '#title' => t('Page Title'),
      '#default_value' => variable_get('nycc_urlto', 'nyccintranet.northyorks.gov.uk'),
      '#size' => 60,
      '#maxlength' => 256,
      '#required' => TRUE,
      '#description' => t('The external url for the intranet site'),
	);
	
	return system_settings_form($form);
  }