name = Standard 2 col
description = A 2 column interior page
template = standard2col-layout

; Regions
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

regions[topsearch]		= Top Search
regions[topmenu]		= Top Menu
regions[topbar]			= Top Bar

regions[2_col_right]	= 2 Col Right Column

; Styles
stylesheets[all][] = css/layouts/standard2col/standard2col.layout.css
stylesheets[all][] = css/layouts/standard2col/standard2col.layout.no-query.css

