name = home
description = The homepage layout
template = home-layout

; Regions
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

regions[topsearch]		= Top Search
regions[topmenu]		= Top Menu
regions[topbar]			= Top Bar

regions[home_news]		= Home News Summary
regions[home_right]		= Home Column Right
regions[home_main]		= Home Main Column

; Styles
stylesheets[all][] = css/layouts/home/home.layout.css
stylesheets[all][] = css/layouts/home/home.layout.no-query.css

; Scripts
scripts[] = js/home-news-respond.js