<?php


function nycc_forms_menu() {
  $items = array();
  $items['forms/redundancy-calculator'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Redundancy calculator', //page title
    'description' => 'Calculate your redundancy pay',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('redundancy_calc_form'), //put the name of the form here
    'access callback' => TRUE
  );

  $items['forms/holiday-entitlement'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Holiday entitlement', //page title
    'description' => 'Calculate your holiday entitlement',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('leave_calc_form'), //put the name of the form here
    'access callback' => TRUE
  );

  $items['forms/maternity-calculator'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Maternity calculator', //page title
    'description' => 'Calculate your maternity entitlement',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('maternity_calc_form'), //put the name of the form here
    'access callback' => TRUE
  );


  return $items;
}



function nycc_forms_block_info() {
        
        $blocks = array();
 

        $blocks['redundancy_calculator_form_block'] = array(
                'info' => t('Redundancy calculator'),
                'cache' => DRUPAL_CACHE_GLOBAL,
        );

         $blocks['holiday_entitlement_form_block'] = array(
                'info' => t('Holiday entitlement'),
                'cache' => DRUPAL_CACHE_GLOBAL,
        );

        $blocks['maternity_calculator_form_block'] = array(
                'info' => t('Maternity Calculator'),
                'cache' => DRUPAL_CACHE_GLOBAL,
        );

        return $blocks;
}

function nycc_forms_block_view($delta = '') {

        $block = array();
 
        switch($delta) {
                case 'redundancy_calculator_form_block':
                        $block['subject'] = t('Redundancy calculator');
                        $block['content'] = drupal_get_form('redundancy_calc_form');
                break;        

                case 'holiday_entitlement_form_block':
                        $block['subject'] = t('Holiday entitlement');
                        $block['content'] = drupal_get_form('leave_calc_form');
                break;        

                case 'maternity_calculator_form_block':
                        $block['subject'] = t('Maternity calculator');
                        $block['content'] = drupal_get_form('maternity_calc_form');   
                break;
        }
 
        return $block;
}



require DRUPAL_ROOT . '/' . drupal_get_path('module', 'nycc_forms') . '/forms/nycc_redundancy.inc';
require DRUPAL_ROOT . '/' . drupal_get_path('module', 'nycc_forms') . '/forms/nycc_leave.inc';
require DRUPAL_ROOT . '/' . drupal_get_path('module', 'nycc_forms') . '/forms/nycc_maternity.inc';

